### ISSUE TITLE
Investigate how improve IAM binding expire error alert

### ISSUE THREAD

**Issue by sqin2019** [abcxyz/access-on-demand#44]
Follow up of https://github.com/abcxyz/access-on-demand/pull/42#discussion_r1231615773
Currently AOD will stop when condition expression format error occurs (in order to remove expired IAM bindings) during IAM policy update.  An improvement could be to continue IAM policy update and alert the error through other means.

**Comment by yolocs** [comment]
Because we run this code in GH workflow, alert without failing the workflow seems challenging. A different idea but will require a little additional work.

Implement a command to clean up expired AOD bindings and run that as a separate step in the workflow. Then we can output a warning to the AOD PR if cleanup fails. This would make the problem more visible.

**Comment by sqin2019** [comment]
> Because we run this code in GH workflow, alert without failing the workflow seems challenging. A different idea but will require a little additional work.
> 
> Implement a command to clean up expired AOD bindings and run that as a separate step in the workflow. Then we can output a warning to the AOD PR if cleanup fails. This would make the problem more visible.

Good idea! We can run this step after iam handle step, so that it won't block iam handle.

**Comment by sqin2019** [comment]
Since now we will implement a [global cleanup in guardian](https://github.com/abcxyz/guardian/issues/145) that cleanup all the iam policies in an org, we will ignore the errors here, all expired IAM bindings and errors will be handled in guardian.
